services:
  api:
    build:
      context: random_backend      
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - random_backend/.env
    environment:
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - 'mysql_data:/var/lib/mysql'
volumes:
  mysql_data:
